name: deploy-code-school

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
      - uses: chrislennon/action-aws-cli@v1.1

      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/code-school/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/code-school/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
